source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sg_postcode'
gem 'minitest'
gem 'minitest-line'
gem 'rest-client'
gem 'simplecov', :require => false, group: :test
gem 'redis'

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# To use a debugger
# gem 'byebug', group: [:development, :test]

